{"syncModifyFlag":1
"cloneDepth":1
"configDeploy":0
"artifactModels":[]
"artifactConfigModels":[]
"branchName":"master"
"branchPattern":-1
"buildTool":1
"buildType":0
"codeQualityServiceModels":[]
"codeUpdateTriggerType":0
"commitId":""
"compileContainer":""
"compileServiceModels":[]
"description":""
"dockerImageTag":{"enableCommitId":1
"enableLatest":0
"enableCodeTag":0
"enableCustom":0
"customPattern":""}
"dynamicBranchConfig":0
"downloadFiles":[]
"eventTriggerModules":[]
"fortifyScanConfig":{"srcPath":""
"scanType":0
"fortifyParam":""
"pythonInstallPath":""
"scalaVersion":""
"gccVersion":""
"cBuildTool":0
"usePrivateImage":0
"rubyPath":""
"rubyGemPath":""
"useQualityGate":false
"pythonVersion":""}
"fortifyScanModules":[]
"gradleVersion":""
"initShell":""
"isSampleProject":0
"jobAddressRelation":{"codeClusterId":5
"codeClusterUrl":"https://code.srdcloud.cn/"
"artifactClusterId":""
"artifactClusterUrl":""
"artifactClusterType":""
"artifactProjectIdentifier":""
"appRootUrl":""
"appRootInnerUrl":""
"gitType":2}
"jobEnvGroups":[]
"jobName":"a1"
"jobTags":[]
"jobType":1
"langVersion":""
"libCache":0
"dockerSave":0
"language":1
"merge":-1
"manualModuleTrigger":0
"node":{"id":"626218377f2e874b78517cb9"
"architecture":"x86"
"type":"cloud"}
"npmOrYarn":1
"notification":{"enableNotification":1
"notifyFailed":1
"notifyTimeout":1
"notifyAbort":0
"notifySuccess":0
"notifyExecutor":1
"notifyManager":0
"notifyMember":0
"notifyDingdingRobot":0
"notifyWechatRobot":0
"dingdingRobotAccounts":[]
"wechatRobotAccounts":[]}
"nodeType":"cloud"
"operationSystem":0
"pipelineTemplateId":-1
"projName":"codefree2025/firstgroup"
"projId":"75945"
"projDisplayName":"第一组"
"parentProjId":75944
"registryModels":[]
"repoName":"kk"
"repoFullName":"codefree2025/firstgroup/kk"
"requirementsPath":""
"scanTool":1
"srcPath":""
"steps":[{"stepIndex":0
"stageGroups":[{"stageGroupParallelIndex":0
"allowDelSteps":1
"artifactType":0
"buildTool":0
"requiredShow":0
"stageGroupId":200
"stageGroupType":15
"async":false
"stageGroupName":"代码下载"
"stageGroupConfig":{"executeCommandConfig":{}
"codeCheckout":{"repoFullName":"codefree2025/firstgroup/kk"
"checkoutPath":"/kk"
"checkoutType":1
"clusterUrl":""
"checkoutParam":"master"
"projId":75945
"repoType":1}}
"guideUrl":"https://www.srdcloud.cn/helpcenter/content?id=1222550295844679680"
"stageGroupDisplayName":"代码下载"}]}]
"scanPath":""
"sonarExclusions":""
"sonarScanConfig":{"gccVersion":""
"cBuildTool":0
"useQualityGate":false
"usePrivateImage":0
"scanPrivateImage":0}
"taasTestModels":[]
"tag":""
"triggerType":1
"triggerDate":""
"triggerMode":1
"triggerTime":""
"triggerTimeFrame":""
"triggerInterval":60
"timeoutMinute":1440
"unitTestServiceModels":[]
"usePrivateImage":0
"verify":1}
